DROP TABLE IF EXISTS tags;

CREATE TABLE tags(
    img_id INTEGER NOT NULL REFERENCES images(id) ON DELETE CASCADE,
    tag VARCHAR(255) NOT NULL,
    PRIMARY KEY (img_id, tag),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
